# Generated by Django 3.0.2 on 2020-04-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(db_index=True, max_length=45, verbose_name='Тип товару')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типи',
                'ordering': ['typ'],
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(db_index=True, max_length=45, verbose_name='Імя товару')),
                ('product_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product_type', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['good_name'],
            },
        ),
    ]
