# Generated by Django 3.0.2 on 2020-04-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prop_laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=45, null=True, verbose_name='Дисплей')),
                ('ram', models.CharField(max_length=45, null=True, verbose_name="Оперативна пам'ять")),
                ('cpu', models.CharField(max_length=45, null=True, verbose_name='Процесор')),
                ('video_card', models.CharField(max_length=45, null=True, verbose_name='Відеокарта')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goods', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Властивість',
                'verbose_name_plural': 'Властивості',
                'ordering': ['id'],
            },
        ),
    ]
