# Generated by Django 3.0.2 on 2020-04-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200408_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.CreateModel(
            name='prop_mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=45, null=True, verbose_name='Дисплей')),
                ('cpu', models.CharField(max_length=45, null=True, verbose_name='Процесор')),
                ('battery', models.CharField(max_length=45, null=True, verbose_name='Батарея')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goods', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Властивість телефону',
                'verbose_name_plural': 'Властивості телефонів',
                'ordering': ['id'],
            },
        ),
    ]
