# Generated by Django 3.0.2 on 2020-04-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200408_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='шлях до малюнку'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product_type', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='counterparties_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Counterparties', verbose_name='контрагент'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goods', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='prop_laptop',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goods', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='prop_mobile',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goods', verbose_name='товар'),
        ),
    ]
